apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://immich-app.github.io/immich-charts
    targetRevision: "0.9.2"
    chart: immich
    helm:
      valuesObject:
        env:
          DB_DATABASE_NAME: immich
          DB_HOSTNAME: immich-pg-cluster-rw.postgres
          DB_PASSWORD: RfU6GE1JAlQaLz5JMRTSoobiSvtfx3c7i0pznzzu4tHYyKHHQNh6SFPC9zQwgGc7
          DB_USERNAME: immich
          REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
        immich:
          persistence:
            library:
              existingClaim: immich-pvc
        machine-learning:
          controller:
            replicas: 2
            strategy: RollingUpdate
          enabled: true
          env:
            TRANSFORMERS_CACHE: /cache
          image:
            pullPolicy: IfNotPresent
            repository: ghcr.io/immich-app/immich-machine-learning
            tag: v1.132.3
          persistence:
            cache:
              accessMode: ReadWriteMany
              enabled: true
              size: 10Gi
              storageClass: rook-cephfs
              type: pvc
        redis:
          architecture: standalone
          auth:
            enabled: false
          enabled: true
        server:
          controller:
            replicas: 2
            strategy: RollingUpdate
          enabled: true
          image:
            pullPolicy: IfNotPresent
            repository: ghcr.io/immich-app/immich-server
            tag: v1.132.3
          ingress:
            main:
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
                nginx.ingress.kubernetes.io/proxy-body-size: '0'
              enabled: true
              hosts:
                - host: photos.cluster.niveri.dev
                  paths:
                    - path: /
              ingressClassName: nginx
              tls:
                - hosts:
                    - photos.cluster.niveri.dev
                  secretName: immich-server-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
