apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slidecontrol
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.cluster.niveri.dev/api/v4/projects/2/packages/helm/stable
    targetRevision: ">=0.0.0"
    chart: slide-control-chart
    helm:
      valuesObject:
        pwaServer:
          ingress:
            main:
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
                nginx.ingress.kubernetes.io/proxy-body-size: '0'
              enabled: true
              hosts:
                - host: slides.cluster.niveri.dev
                  paths:
                    - path: /
              ingressClassName: nginx
              tls:
                - hosts:
                    - slides.cluster.niveri.dev
                  secretName: slidecontrol-tls
        server:
          ingress:
            main:
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
                nginx.ingress.kubernetes.io/proxy-body-size: '0'
              enabled: true
              hosts:
                - host: slides.cluster.niveri.dev
                  paths:
                    - path: /socket
              ingressClassName: nginx
              tls:
                - hosts:
                    - slides.cluster.niveri.dev
                  secretName: slidecontrol-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: slidecontrol
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
