apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internal
  namespace: metallb-system
spec:
  addresses:
  - 10.0.0.0/24
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public
  namespace: metallb-system
spec:
  addresses:
  - 91.99.10.215-91.99.10.215
  serviceAllocation:
    priority: 1
    namespaces:
      - ingress-nginx
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-envoy
  namespace: metallb-system
spec:
  addresses:
  - 91.107.238.152-91.107.238.152
  serviceAllocation:
    priority: 1
    namespaces:
      - envoy-gateway-system
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: internal-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - internal
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - public
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: falkenberg.kubenix.niveri.dev
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-envoy-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - public-envoy
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: stadeln.kubenix.niveri.dev
